configuration:
  - Release
  - Debug

before_build:
  nuget restore ./src/Transducers.Net.sln

build:
  project: ./src/Transducers.Net.sln

test:
  assemblies:
    - Tests.dll

notifications:
  - provider: Slack
    auth_token:
      secure: xoxp-3423826649-3423826655-19299331236-06018cef84
    channel: git